(function(){
const root=document.querySelector('[data-investment-lab]');if(!root)return;
const rawData=window.FG_LAB_DATA||{};
const DATA=typeof rawData==='string'?JSON.parse(rawData):rawData;
DATA.articles=Array.isArray(DATA.articles)?DATA.articles:[];
DATA.locations=Array.isArray(DATA.locations)?DATA.locations:[];
DATA.lexicon=Array.isArray(DATA.lexicon)?DATA.lexicon:[];
const eur=v=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(isFinite(v)?v:0);
const pct=v=>new Intl.NumberFormat('de-DE',{style:'percent',maximumFractionDigits:2}).format(isFinite(v)?v:0);
const de=v=>new Intl.NumberFormat('de-DE',{maximumFractionDigits:2}).format(isFinite(v)?v:0);
const parse=v=>{let s=String(v??'').replace(/\s|€|%/g,'');if(s.includes(','))s=s.replace(/\./g,'').replace(',','.');return parseFloat(s)||0};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function switchTab(name){root.querySelectorAll('[data-lab-tab]').forEach(b=>b.classList.toggle('is-active',b.dataset.labTab===name));root.querySelectorAll('[data-lab-panel]').forEach(p=>p.classList.toggle('is-active',p.dataset.labPanel===name));root.scrollIntoView({behavior:'smooth',block:'start'});}
document.addEventListener('click',e=>{let t=e.target.closest('[data-lab-tab],[data-lab-open]');if(!t)return;let name=t.dataset.labTab||t.dataset.labOpen;if(name)switchTab(name)});

const tools=[
{id:'investment',icon:'chart-line',title:'Investitionsrechner',desc:'Vollständige Objekt-, Finanzierungs-, Steuer- und Verlaufsrechnung.',link:'/investitionsrechner.html'},
{id:'afford',icon:'home',title:'Wie viel Immobilie kann ich mir leisten?',desc:'Monatsrate, Eigenkapital, Zins, Tilgung und Nebenkosten zu einem Kaufpreisrahmen verbinden.'},
{id:'closing',icon:'receipt',title:'Kaufnebenkostenrechner',desc:'Grunderwerbsteuer nach Bundesland, Notar, Grundbuch und Makler berechnen.'},
{id:'cashflow',icon:'coins',title:'Cashflow-Schnellcheck',desc:'Mit fünf Eingaben den monatlichen Überschuss vor Steuer abschätzen.'},
{id:'loan',icon:'landmark',title:'Darlehens- und Restschuldrechner',desc:'Annuität, Zins, Tilgung und Restschuld dynamisch berechnen.'},
{id:'yield',icon:'percentage',title:'Mietrenditerechner',desc:'Brutto- und Nettomietrendite mit transparenten Kosten.'},
{id:'afa',icon:'building',title:'AfA-Rechner',desc:'Gebäudeanteil, AfA-Basis und jährliche Abschreibung als Szenario.'},
{id:'tax',icon:'file-invoice-dollar',title:'Steuerersparnisrechner',desc:'Vereinfachte Steuerwirkung aus Zins, AfA und Überschuss.'},
{id:'rentgrowth',icon:'arrow-trend-up',title:'Mietsteigerungsrechner',desc:'Miete und kumulierte Erträge über die Zeit projizieren.'},
{id:'equity',icon:'wallet',title:'Eigenkapitalrechner',desc:'Erforderliches Eigenkapital aus Kaufpreis, Quote und Nebenkosten.'},
{id:'exit',icon:'door-open',title:'Exit-Rechner',desc:'Verkaufserlös, Restschuld, Kosten und Netto-Rückfluss modellieren.'},
{id:'interest',icon:'wave-square',title:'Zinsänderungsrechner',desc:'Was passiert mit Rate und Anschlussbelastung, wenn der Zins steigt?'},
{id:'value',icon:'city',title:'Immobilienwert-Prognose',desc:'Konservative Szenarien für Wertentwicklung und Endwert.'},
{id:'portfolio',icon:'layer-group',title:'Portfolio-Rechner',desc:'Mehrere Objekte als einfaches Portfolio zusammenfassen.'},
{id:'compare',icon:'scale-balanced',title:'Zwei Immobilien vergleichen',desc:'Kaufpreis, Miete, Cashflow und Rendite nebeneinanderstellen.'},
{id:'sensitivity',icon:'sliders',title:'Sensitivitätsanalyse',desc:'Zins, Miete, Leerstand und Kaufpreis als Tornado-Diagramm testen.'}
];
const grid=root.querySelector('[data-tool-grid]'), workspace=root.querySelector('[data-lab-workspace]');
function renderTools(q=''){let z=q.toLowerCase();grid.innerHTML=tools.filter(t=>(t.title+' '+t.desc).toLowerCase().includes(z)).map(t=>`<article class="lab-tool-card"><i class="fas fa-${t.icon}"></i><h3>${t.title}</h3><p>${t.desc}</p>${t.link?`<a href="${t.link}" class="lab-card-action">Öffnen <span>→</span></a>`:`<button class="lab-card-action" data-tool="${t.id}">Öffnen <span>→</span></button>`}</article>`).join('')}
renderTools();root.querySelector('[data-tool-search]').addEventListener('input',e=>renderTools(e.target.value));
grid.addEventListener('click',e=>{let b=e.target.closest('[data-tool]');if(b)openTool(b.dataset.tool)});
const field=(name,label,val='',suffix='',type='number')=>`<label class="lab-field"><span>${label}</span><div><input name="${name}" type="${type}" value="${val}" inputmode="decimal">${suffix?`<b>${suffix}</b>`:''}</div></label>`;
const formWrap=(tool,fields,extra='')=>`<div class="lab-work-head"><div><button data-close-tool class="lab-back-button"><i class="fas fa-arrow-left"></i><span><small>Zurück zu</small>Rechnerübersicht</span></button><span class="lab-kicker">${tool.title.toUpperCase()}</span><h2>${tool.title}</h2><p>${tool.desc}</p></div></div><form data-tool-form="${tool.id}" class="lab-calc-form"><div class="lab-fields">${fields}</div>${extra}<div class="lab-form-actions"><button class="lab-btn lab-btn-gold" type="submit">Ergebnis berechnen</button></div></form><div data-tool-result class="lab-tool-result"></div>`;
function openTool(id){let t=tools.find(x=>x.id===id);workspace.hidden=false;grid.hidden=true;let f='',extra='';
 if(id==='afford')f=field('rate','Verfügbare Monatsrate',1800,'€')+field('equity','Eigenkapital',80000,'€')+field('interest','Sollzins p.a.',4.2,'%')+field('repay','Anfängliche Tilgung p.a.',2,'%')+field('costs','Kaufnebenkosten',10,'%');
 if(id==='closing')f=field('price','Kaufpreis',400000,'€')+`<label class="lab-field"><span>Bundesland</span><div><select name="state">${Object.entries(taxRates).map(([k,v])=>`<option value="${v}">${k} (${de(v)} %)</option>`).join('')}</select></div></label>`+field('broker','Makler inkl. MwSt.',3.57,'%')+field('notary','Notar',1.5,'%')+field('land','Grundbuch',0.5,'%');
 if(id==='cashflow')f=field('rent','Monatliche Nettokaltmiete',1200,'€')+field('loan','Darlehenssumme',250000,'€')+field('interest','Sollzins p.a.',4.2,'%')+field('repay','Tilgung p.a.',2,'%')+field('costs','Eigentümerkosten mtl.',250,'€');
 if(id==='loan')f=field('loan','Darlehen',300000,'€')+field('interest','Sollzins p.a.',4.2,'%')+field('repay','Anfängliche Tilgung p.a.',2,'%')+field('years','Zeitraum',10,'Jahre');
 if(id==='yield')f=field('price','Kaufpreis',300000,'€')+field('rent','Monatsnettokaltmiete',1200,'€')+field('costs','Nicht umlagefähige Kosten mtl.',180,'€')+field('vacancy','Mietausfall',2,'%')+field('reserve','Rücklage p.a.',1200,'€');
 if(id==='afa')f=field('price','Kaufpreis inkl. zuordenbarer Nebenkosten',350000,'€')+field('share','Gebäudeanteil',75,'%')+field('rate','AfA-Satz',2,'%')+field('years','Betrachtung',10,'Jahre');
 if(id==='tax')f=field('rent','Jahresnettokaltmiete',18000,'€')+field('costs','Abziehbare Kosten ohne Zins/AfA',3500,'€')+field('interest','Zinsen im Jahr',10000,'€')+field('afa','AfA im Jahr',6000,'€')+field('tax','Persönlicher Steuersatz',42,'%');
 if(id==='rentgrowth')f=field('rent','Aktuelle Monatsmiete',1200,'€')+field('growth','Mietsteigerung p.a.',2,'%')+field('years','Zeitraum',10,'Jahre');
 if(id==='equity')f=field('price','Kaufpreis',400000,'€')+field('costs','Nebenkosten',10,'%')+field('quote','Finanzierungsquote vom Kaufpreis',90,'%')+field('invest','Anfangsinvestitionen',20000,'€');
 if(id==='exit')f=field('value','Heutiger Immobilienwert',400000,'€')+field('growth','Wertsteigerung p.a.',2,'%')+field('years','Haltedauer',10,'Jahre')+field('debt','Restschuld beim Exit',250000,'€')+field('costs','Verkaufskosten',3.57,'%');
 if(id==='interest')f=field('debt','Restschuld',300000,'€')+field('repay','Tilgung p.a.',2,'%')+field('base','Basiszins',3.5,'%')+field('stress','Stresszins',5.5,'%');
 if(id==='value')f=field('value','Heutiger Wert',400000,'€')+field('growth','Wertsteigerung p.a.',2,'%')+field('years','Zeitraum',10,'Jahre');
 if(id==='portfolio')f=field('values','Gesamtwert Portfolio',1500000,'€')+field('debt','Gesamtdarlehen',900000,'€')+field('rent','Jahresnettokaltmiete',90000,'€')+field('costs','Eigentümerkosten p.a.',18000,'€')+field('service','Kapitaldienst p.a.',60000,'€');
 if(id==='compare')f=['a','b'].map((x,i)=>`<fieldset><legend>Objekt ${i+1}</legend>${field(x+'price','Kaufpreis',i?350000:300000,'€')}${field(x+'rent','Monatsmiete',i?1400:1200,'€')}${field(x+'costs','Kosten mtl.',i?220:180,'€')}</fieldset>`).join('');
 if(id==='sensitivity')f=field('price','Kaufpreis',400000,'€')+field('rent','Monatsmiete',1600,'€')+field('loan','Darlehen',360000,'€')+field('interest','Zins p.a.',4,'%')+field('repay','Tilgung p.a.',2,'%')+field('costs','Kosten mtl.',250,'€');
 workspace.innerHTML=formWrap(t,f,extra);workspace.scrollIntoView({behavior:'smooth',block:'start'});workspace.querySelector('[data-close-tool]').onclick=()=>{workspace.hidden=true;grid.hidden=false};workspace.querySelector('form').onsubmit=e=>{e.preventDefault();calcTool(id,new FormData(e.target),workspace.querySelector('[data-tool-result]'))};}
const taxRates={'Baden-Württemberg':5,'Bayern':3.5,'Berlin':6,'Brandenburg':6.5,'Bremen':5,'Hamburg':5.5,'Hessen':6,'Mecklenburg-Vorpommern':6,'Niedersachsen':5,'Nordrhein-Westfalen':6.5,'Rheinland-Pfalz':5,'Saarland':6.5,'Sachsen':5.5,'Sachsen-Anhalt':5,'Schleswig-Holstein':6.5,'Thüringen':6.5};
function annuity(loan,interest,repay,years=1){let rate=loan*(interest+repay)/12,debt=loan,ints=0,prin=0;for(let m=0;m<years*12&&debt>0;m++){let i=debt*interest/12,p=Math.min(debt,Math.max(0,rate-i));ints+=i;prin+=p;debt-=p}return{rate,debt,interest:ints,principal:prin}}
function resultHtml(kpis,note='',chart=''){return `<div class="lab-result-kpis">${kpis.map(k=>`<article><span>${k[0]}</span><strong>${k[1]}</strong><small>${k[2]||''}</small></article>`).join('')}</div>${chart}${note?`<p class="lab-result-note">${note}</p>`:''}<div class="lab-result-actions"><button data-save-calc class="lab-btn lab-btn-ghost">Lokal speichern</button><button data-print-calc class="lab-btn lab-btn-ghost"><i class="fas fa-file-pdf"></i> Als PDF drucken</button><a href="/ankaufsberatung.html" class="lab-btn lab-btn-gold">Ergebnis besprechen</a></div>`}
function calcTool(id,fd,out){let v=k=>parse(fd.get(k)),k=[],note='',chart='';
 if(id==='afford'){let rate=v('rate'),e=v('equity'),i=v('interest')/100,t=v('repay')/100,c=v('costs')/100,loan=rate*12/(i+t),price=(loan+e)/(1+c);k=[['Möglicher Kaufpreis',eur(price),'Orientierungswert'],['Darlehensrahmen',eur(loan)],['Gesamtbudget inkl. Nebenkosten',eur(price*(1+c))],['Monatliche Rate',eur(rate)]]}
 if(id==='closing'){let p=v('price'),tax=v('state'),a=p*tax/100,b=p*v('broker')/100,n=p*v('notary')/100,l=p*v('land')/100,total=a+b+n+l;k=[['Nebenkosten gesamt',eur(total),pct(total/p)+' des Kaufpreises'],['Grunderwerbsteuer',eur(a)],['Makler',eur(b)],['Notar & Grundbuch',eur(n+l)],['Gesamtinvestition',eur(p+total)]]}
 if(id==='cashflow'){let rent=v('rent'),a=annuity(v('loan'),v('interest')/100,v('repay')/100),cf=rent-a.rate-v('costs');k=[['Cashflow pro Monat',eur(cf),cf>=0?'rechnerischer Überschuss':'rechnerischer Zuschuss'],['Annuität pro Monat',eur(a.rate)],['Miete',eur(rent)],['Eigentümerkosten',eur(v('costs'))]]}
 if(id==='loan'){let a=annuity(v('loan'),v('interest')/100,v('repay')/100,v('years'));k=[['Monatliche Annuität',eur(a.rate)],['Restschuld',eur(a.debt)],['Gezahlte Zinsen',eur(a.interest)],['Getilgt',eur(a.principal)]]}
 if(id==='yield'){let annual=v('rent')*12,gross=annual/v('price'),net=(annual*(1-v('vacancy')/100)-v('costs')*12-v('reserve'))/v('price');k=[['Bruttomietrendite',pct(gross)],['Nettomietrendite',pct(net)],['Jahresnettokaltmiete',eur(annual)],['Nettoertrag',eur(net*v('price'))]]}
 if(id==='afa'){let base=v('price')*v('share')/100,annual=base*v('rate')/100;k=[['AfA-Basis',eur(base)],['AfA pro Jahr',eur(annual)],['Kumuliert',eur(annual*v('years'))],['Nicht abschreibbarer Anteil',eur(v('price')-base)]];note='Vereinfachtes Szenario. Steuerliche Zuordnung und anwendbarer AfA-Satz müssen individuell geprüft werden.'}
 if(id==='tax'){let income=v('rent')-v('costs')-v('interest')-v('afa'),tax=income*v('tax')/100;k=[['Steuerliches Ergebnis',eur(income)],['Vereinfachte Steuerwirkung',eur(tax)],['Liquidität vor Tilgung',eur(v('rent')-v('costs')-v('interest')-tax)],['AfA',eur(v('afa'))]]}
 if(id==='rentgrowth'){let r=v('rent'),g=v('growth')/100,y=v('years'),end=r*Math.pow(1+g,y),cum=0;for(let n=1;n<=y;n++)cum+=r*12*Math.pow(1+g,n-1);k=[['Monatsmiete am Ende',eur(end)],['Jahresmiete am Ende',eur(end*12)],['Kumulierte Miete',eur(cum)],['Gesamtanstieg',pct(end/r-1)]]}
 if(id==='equity'){let p=v('price'),cost=p*v('costs')/100,loan=p*v('quote')/100,need=p+cost+v('invest')-loan;k=[['Erforderliches Eigenkapital',eur(need)],['Darlehen',eur(loan)],['Nebenkosten',eur(cost)],['Gesamtinvestition',eur(p+cost+v('invest'))]]}
 if(id==='exit'){let end=v('value')*Math.pow(1+v('growth')/100,v('years')),cost=end*v('costs')/100,net=end-cost-v('debt');k=[['Prognostizierter Verkaufspreis',eur(end)],['Verkaufskosten',eur(cost)],['Restschuld',eur(v('debt'))],['Netto-Rückfluss',eur(net)]]}
 if(id==='interest'){let base=annuity(v('debt'),v('base')/100,v('repay')/100),stress=annuity(v('debt'),v('stress')/100,v('repay')/100);k=[['Rate Basiszins',eur(base.rate)],['Rate Stresszins',eur(stress.rate)],['Mehrbelastung pro Monat',eur(stress.rate-base.rate)],['Mehrbelastung pro Jahr',eur((stress.rate-base.rate)*12)]]}
 if(id==='value'){let end=v('value')*Math.pow(1+v('growth')/100,v('years'));k=[['Endwert Szenario',eur(end)],['Nominaler Zuwachs',eur(end-v('value'))],['Wachstum gesamt',pct(end/v('value')-1)],['Startwert',eur(v('value'))]]}
 if(id==='portfolio'){let net=v('rent')-v('costs'),dscr=net/v('service'),ltv=v('debt')/v('values');k=[['Portfoliowert',eur(v('values'))],['LTV',pct(ltv)],['Nettoertrag vor Finanzierung',eur(net)],['DSCR',de(dscr)+'x']];note='Vereinfachte Portfoliosicht. Banken können DSCR und Beleihungswerte anders definieren.'}
 if(id==='compare'){let calc=x=>({gross:v(x+'rent')*12/v(x+'price'),net:v(x+'rent')*12-v(x+'costs')*12});let a=calc('a'),b=calc('b');k=[['Bruttorendite Objekt 1',pct(a.gross)],['Bruttorendite Objekt 2',pct(b.gross)],['Nettoertrag Objekt 1',eur(a.net)],['Nettoertrag Objekt 2',eur(b.net)]]}
 if(id==='sensitivity'){let base=v('rent')*12-v('costs')*12-v('loan')*(v('interest')+v('repay'))/100;let scenarios=[['Zins +1 %-Punkt',base-v('loan')*.01],['Miete -10 %',base-v('rent')*12*.1],['Kosten +20 %',base-v('costs')*12*.2],['Kaufpreis -10 %',base],['Miete +3 %',base+v('rent')*12*.03]];let max=Math.max(...scenarios.map(x=>Math.abs(x[1]-base)),1);chart=`<div class="lab-tornado"><h3>Abweichung vom Basis-Cashflow (${eur(base)} p.a.)</h3>${scenarios.map(s=>{let d=s[1]-base,w=Math.abs(d)/max*48;return `<div><span>${s[0]}</span><i class="${d>=0?'pos':'neg'}" style="width:${w}%"></i><b>${eur(d)}</b></div>`}).join('')}</div>`;k=[['Basis-Cashflow p.a.',eur(base)],['Basis-Cashflow mtl.',eur(base/12)],['Stärkster negativer Effekt',eur(Math.min(...scenarios.map(x=>x[1]-base)))],['Miete +3 %',eur(base+v('rent')*12*.03)]]}
 out.innerHTML=resultHtml(k,note,chart);out.scrollIntoView({behavior:'smooth',block:'nearest'});out.querySelector('[data-save-calc]').onclick=()=>saveCalc(id,k);out.querySelector('[data-print-calc]').onclick=()=>printCalculatorReport(id,fd,k,note,chart)}
function saveCalc(id,k){let arr=JSON.parse(localStorage.getItem('fgLabSaved')||'[]');arr.unshift({id,title:tools.find(t=>t.id===id)?.title,date:new Date().toLocaleDateString('de-DE'),k});arr=arr.slice(0,12);localStorage.setItem('fgLabSaved',JSON.stringify(arr));renderSaved()}
function renderSaved(){let box=root.querySelector('[data-lab-saved]'),arr=JSON.parse(localStorage.getItem('fgLabSaved')||'[]');box.innerHTML=arr.length?`<div class="lab-section-head"><div><span class="lab-kicker">GESPEICHERTE BERECHNUNGEN</span><h2>Auf diesem Gerät gespeichert</h2></div><button class="lab-clear" data-clear-saved>Alle löschen</button></div><div class="lab-saved-grid">${arr.map((x,i)=>`<article><small>${x.date}</small><h3>${x.title}</h3>${x.k.slice(0,2).map(y=>`<p><span>${y[0]}</span><strong>${y[1]}</strong></p>`).join('')}<button data-delete-saved="${i}">Löschen</button></article>`).join('')}</div>`:'';box.querySelector('[data-clear-saved]')?.addEventListener('click',()=>{localStorage.removeItem('fgLabSaved');renderSaved()});box.querySelectorAll('[data-delete-saved]').forEach(b=>b.onclick=()=>{arr.splice(+b.dataset.deleteSaved,1);localStorage.setItem('fgLabSaved',JSON.stringify(arr));renderSaved()})}renderSaved();


function formulaForArticle(title,category){
 const t=(title||'').toLowerCase();
 if(t.includes('annuität')) return {title:'Mathematisches Modell des Annuitätendarlehens',html:`
 <div class="lab-formula-card"><p><strong>Anfängliche Jahresannuität:</strong></p><div class="lab-formula">A = K₀ · (i + t₀)</div><p>K₀ bezeichnet die anfängliche Darlehenssumme, i den nominalen Sollzinssatz pro Jahr und t₀ die anfängliche Tilgung. Bei monatlicher Zahlung gilt näherungsweise Aₘ = A / 12.</p></div>
 <div class="lab-formula-card"><p><strong>Monatliche Fortschreibung:</strong></p><div class="lab-formula">Zₘ = Kₘ₋₁ · i / 12</div><div class="lab-formula">Tₘ = Aₘ − Zₘ</div><div class="lab-formula">Kₘ = Kₘ₋₁ − Tₘ</div><p>Mit sinkender Restschuld Kₘ fällt der Zinsanteil Zₘ. Weil die Rate Aₘ konstant bleibt, steigt der Tilgungsanteil Tₘ entsprechend.</p></div>
 <div class="lab-formula-card"><p><strong>Geschlossene Restschuldformel bei konstanter Periodenrate:</strong></p><div class="lab-formula">Kₙ = K₀(1+r)ⁿ − Aₚ · Σ<sub>j=0</sub><sup>n−1</sup>(1+r)ʲ</div><div class="lab-formula">Kₙ = K₀(1+r)ⁿ − Aₚ · ((1+r)ⁿ−1)/r</div><p>r ist der periodische Zinssatz und Aₚ die Rate je Periode. Die Summenform zeigt, dass jede Rate die bis zum Zeitpunkt n aufgelaufene Schuld reduziert.</p></div>`};
 if(t.includes('eigenkapitalrendite')) return {title:'Berechnungslogik',html:`<div class="lab-formula-card"><div class="lab-formula">EK-Rendite = (Cashflow nach Steuer + Tilgung + optionaler Wertzuwachs) / eingesetztes Eigenkapital</div><p>Wertzuwachs sollte separat ausgewiesen werden. Für Vergleichbarkeit müssen Kaufnebenkosten, Anfangsinvestitionen und tatsächlich gebundenes Eigenkapital vollständig im Nenner stehen.</p></div>`};
 if(t.includes('cashflow')) return {title:'Berechnungslogik',html:`<div class="lab-formula-card"><div class="lab-formula">Cashflow vor Steuer = Nettokaltmiete − Eigentümerkosten − Zinsen − Tilgung</div><div class="lab-formula">Cashflow nach Steuer = Cashflow vor Steuer − Steuerzahlung bzw. + Steuerentlastung</div><p>Tilgung ist ein Liquiditätsabfluss, aber grundsätzlich keine steuerlich abzugsfähige Ausgabe. AfA wirkt steuerlich, ohne im jeweiligen Jahr einen Zahlungsabfluss auszulösen.</p></div>`};
 if(t.includes('brutto')||t.includes('mietrendite')) return {title:'Berechnungslogik',html:`<div class="lab-formula-card"><div class="lab-formula">Bruttomietrendite = Jahresnettokaltmiete / Kaufpreis</div><div class="lab-formula">Nettomietrendite = (Jahresnettokaltmiete − laufende Eigentümerkosten − Mietausfall) / Gesamtinvestition</div><p>In der Praxis existieren unterschiedliche Definitionen der Nettomietrendite. Deshalb muss die verwendete Kosten- und Investitionsbasis immer offengelegt werden.</p></div>`};
 if(t.includes('afa')||t.includes('abschreibung')) return {title:'Berechnungslogik',html:`<div class="lab-formula-card"><div class="lab-formula">AfA-Bemessungsgrundlage = anschaffungsnahe Gebäudekosten</div><div class="lab-formula">Jährliche AfA = AfA-Bemessungsgrundlage · AfA-Satz</div><p>Grund und Boden ist nicht abschreibbar. Kaufnebenkosten werden regelmäßig im Verhältnis der Kaufpreisaufteilung zugeordnet. Der konkret zulässige Satz hängt vom Objekt und der steuerlichen Einordnung ab.</p></div>`};
 if(t.includes('kaufpreisfaktor')) return {title:'Berechnungslogik',html:`<div class="lab-formula-card"><div class="lab-formula">Kaufpreisfaktor = Kaufpreis / Jahresnettokaltmiete</div><div class="lab-formula">Bruttomietrendite = 1 / Kaufpreisfaktor</div><p>Ein Faktor von 20 entspricht rechnerisch einer Bruttomietrendite von 5 %. Laufende Kosten, Investitionen und Finanzierung bleiben dabei unberücksichtigt.</p></div>`};
 if(t.includes('beleihung')||t.includes('ltv')) return {title:'Berechnungslogik',html:`<div class="lab-formula-card"><div class="lab-formula">LTV = Darlehenssaldo / Immobilienwert</div><div class="lab-formula">Beleihungsauslauf = Darlehen / bankseitiger Beleihungswert</div><p>Der bankseitige Beleihungswert kann unter dem Kaufpreis oder Marktwert liegen. Daher sind Finanzierungsquote und Beleihungsauslauf nicht identisch.</p></div>`};
 return {title:'Analytischer Rahmen',html:`<div class="lab-formula-card"><p>Der Begriff wird im Investment Lab nicht isoliert betrachtet. Für eine belastbare Einordnung werden Zahlungsströme, Zeitraum, Risiken und die jeweilige Bezugsgröße getrennt erfasst. Mathematische Kennzahlen sind nur dann vergleichbar, wenn Zähler, Nenner und Betrachtungszeitraum einheitlich definiert sind.</p></div>`};
}
function articleSections(a){
 const f=formulaForArticle(a.title,a.category);
 const title=(a.title||'').toLowerCase();
 const annuity=title.includes('annuität');
 const advantages=annuity?['Hohe Planbarkeit der Rate innerhalb der Zinsbindung.','Automatisch steigender Tilgungsanteil bei sinkender Restschuld.','Einfache Vergleichbarkeit unterschiedlicher Zins- und Tilgungsszenarien.']:['Strukturierte Einordnung eines komplexen Sachverhalts.','Kennzahlen und Annahmen werden voneinander getrennt.','Szenarien lassen sich transparent vergleichen.'];
 const limits=annuity?['Die Rate kann nach Ende der Zinsbindung deutlich steigen.','Eine niedrige Anfangstilgung führt häufig zu hoher Restschuld.','Sondertilgungen, Bereitstellungszinsen und Gebühren müssen separat modelliert werden.']:['Das Ergebnis hängt von Datenqualität und Begriffsdefinition ab.','Rechtliche, steuerliche und technische Besonderheiten können nicht pauschalisiert werden.','Markt- und Wertannahmen sind Szenarien, keine Garantien.'];
 return `<button data-reader-back class="lab-back-button"><i class="fas fa-arrow-left"></i><span><small>Zurück zu</small>Immobilienwissen</span></button>
 <header class="lab-detail-header"><span class="lab-kicker">${esc(a.category)}</span><h2>${esc(a.title)}</h2><p class="lab-lead">${esc(a.summary)}</p></header>
 <section class="lab-science-section"><h3>1. Definition und ökonomische Bedeutung</h3><p>${esc(a.body)}</p><p>Für eine wissenschaftlich nachvollziehbare Analyse ist zunächst festzulegen, welche Größen betrachtet werden, auf welchen Zeitpunkt sie sich beziehen und ob nominale oder reale Werte verwendet werden. Nur so lassen sich Ergebnisse zwischen Objekten oder Finanzierungsvarianten sinnvoll vergleichen.</p></section>
 <section class="lab-science-section"><h3>2. ${f.title}</h3>${f.html}</section>
 <section class="lab-science-section"><h3>3. Schrittweise Anwendung</h3><ol><li>Alle Eingangsgrößen und ihren Bezugszeitraum eindeutig bestimmen.</li><li>Kosten, Finanzierung, Steuern und Wertentwicklung getrennt modellieren.</li><li>Ein Basisszenario sowie mindestens ein konservatives Stressszenario rechnen.</li><li>Ergebnis nicht nur als Prozentwert, sondern zusätzlich als Eurobetrag und Verlauf betrachten.</li><li>Annahmen anhand von Verträgen, Abrechnungen, Gutachten und Marktinformationen überprüfen.</li></ol></section>
 <div class="lab-pro-con"><section><h3>Vorteile</h3><ul>${advantages.map(x=>`<li>${x}</li>`).join('')}</ul></section><section><h3>Grenzen und Risiken</h3><ul>${limits.map(x=>`<li>${x}</li>`).join('')}</ul></section></div>
 <section class="lab-science-section"><h3>4. Praxisbeispiel und Interpretation</h3><p>Ein Rechenergebnis ist kein Urteil über ein Investment. Es zeigt, wie sich die gewählten Annahmen mathematisch auswirken. Besonders wichtig ist die Trennung zwischen laufender Liquidität, Vermögensaufbau durch Tilgung, steuerlicher Wirkung und unsicherer Wertentwicklung.</p></section>
 <aside class="lab-practice-box"><strong>Prüfungshinweis</strong><p>Nutzen Sie den passenden Rechner im Investment Lab. Prüfen Sie anschließend, ob die verwendeten Werte mit den Objektunterlagen und dem Finanzierungsvorschlag übereinstimmen.</p></aside>
 <div class="lab-reader-links"><button data-reader-tools class="lab-btn lab-btn-gold">Passenden Rechner öffnen</button><a href="/angebote.html" class="lab-btn lab-btn-ghost">Aktuelle Angebote</a></div>`;
}
function inferLexCategory(term){const t=term.toLowerCase();if(/afa|steuer|abschreibung|werbungskosten|spekulation/.test(t))return'Steuern';if(/darlehen|zins|tilgung|annuit|beleih|ltv|dscr|bonität|grundschuld|finanz/.test(t))return'Finanzierung';if(/miete|hausgeld|weg|leerstand|umlage|betriebskosten/.test(t))return'Vermietung';if(/rendite|cashflow|faktor|portfolio|exit|capex/.test(t))return'Kapitalanlage';return'Immobilienkauf'}
function specialLexicon(x){
 const t=x.term.toLowerCase();
 if(t.includes('maklerprovision')||t.includes('maklercourtage')) return `<section class="lab-science-section"><h3>Rechtliche und wirtschaftliche Einordnung</h3><p>Die Maklercourtage ist die erfolgsabhängige Vergütung für den Nachweis einer Abschlussgelegenheit oder die Vermittlung eines Hauptvertrags. Beim Immobilienkauf ist die Höhe grundsätzlich verhandelbar; eine bundesweit gesetzlich festgelegte Höchstprovision gibt es für Kaufobjekte nicht. Regionale Marktgewohnheiten sind deshalb keine rechtliche Obergrenze.</p><p>Für den Kauf einer Wohnung oder eines Einfamilienhauses durch einen Verbraucher gelten besondere Regeln: Der Maklervertrag bedarf der Textform. Ist der Makler für beide Kaufvertragsparteien tätig, müssen sich beide in gleicher Höhe zur Zahlung verpflichten. Hat nur eine Seite den Makler beauftragt und soll die andere Seite Kosten übernehmen, muss die beauftragende Seite mindestens in gleicher Höhe verpflichtet bleiben. Diese Teilungsregeln erfassen nicht automatisch Mehrfamilienhäuser, Gewerbeobjekte, unbebaute Grundstücke oder Käufe, bei denen der Erwerber nicht als Verbraucher handelt.</p></section><section class="lab-science-section"><h3>Objektarten unterscheiden</h3><ul><li><strong>Eigentumswohnung:</strong> Bei Verbraucherkäufen greifen regelmäßig die §§ 656a–656d BGB zur Textform und Kostenverteilung.</li><li><strong>Einfamilienhaus:</strong> Ebenfalls vom besonderen Verbraucherschutz der §§ 656a–656d BGB erfasst.</li><li><strong>Mehrfamilienhaus:</strong> Die gesetzlichen Teilungsvorschriften gelten hierfür grundsätzlich nicht allein wegen der Wohnnutzung; die Vergütung und Kostentragung werden vertraglich vereinbart.</li><li><strong>Vermietung von Wohnraum:</strong> Hier gilt das Bestellerprinzip; bei Zahlung durch den Wohnungssuchenden ist die Vergütung gesetzlich begrenzt.</li></ul></section><section class="lab-science-section"><h3>Berechnung</h3><div class="lab-formula-card"><div class="lab-formula">Courtage brutto = Kaufpreis · Provisionssatz</div><p>Bei einem Kaufpreis von 500.000 € und 3,57 % Käufercourtage beträgt der Käuferanteil 17.850 €. Entscheidend ist, ob der Prozentsatz bereits Umsatzsteuer enthält.</p></div></section>`;
 if(t==='annuität') return `<section class="lab-science-section"><h3>Mathematische Bedeutung</h3><p>Die Annuität ist die innerhalb eines vereinbarten Zeitraums konstante periodische Zahlung eines Annuitätendarlehens. Sie besteht aus Zins und Tilgung.</p><div class="lab-formula-card"><div class="lab-formula">Aₘ = K₀ · (i + t₀) / 12</div><div class="lab-formula">Zₘ = Kₘ₋₁ · i / 12</div><div class="lab-formula">Tₘ = Aₘ − Zₘ</div></div><p>Weil der Zins auf die jeweils verbleibende Restschuld berechnet wird, sinkt der Zinsanteil und der Tilgungsanteil steigt.</p></section>`;
 return '';
}
function lexiconDetail(x){const cat=inferLexCategory(x.term),special=specialLexicon(x);return `<button data-lex-back class="lab-back-button"><i class="fas fa-arrow-left"></i><span><small>Zurück zum</small>Immobilienlexikon</span></button><header class="lab-detail-header"><span class="lab-kicker">${cat.toUpperCase()}</span><h2>${esc(x.term)}</h2><p class="lab-lead">${esc(x.definition)}</p></header>${special||`<section class="lab-science-section"><h3>Ausführliche Definition</h3><p>${esc(x.definition)} Der Begriff ist für Immobilienentscheidungen relevant, weil er entweder eine rechtliche Position, einen Zahlungsstrom, eine Bewertungsgröße oder ein objektspezifisches Risiko beschreibt.</p></section><section class="lab-science-section"><h3>Einordnung in der Praxis</h3><p>Vor einer Berechnung muss geklärt werden, wie der Begriff im konkreten Vertrag, in der Abrechnung oder im Finanzierungsvorschlag definiert ist. Gleichlautende Kennzahlen können je nach Datenquelle unterschiedliche Bestandteile enthalten.</p></section><section class="lab-science-section"><h3>Berechnung und Zusammenhänge</h3><div class="lab-formula-card"><p>Wo eine mathematische Berechnung möglich ist, sind Bezugsgröße, Zeitraum und Vorzeichen offenzulegen. Prozentwerte sollten immer zusätzlich als Eurobetrag dargestellt und mit einem Vergleichsszenario geprüft werden.</p></div></section>`}<section class="lab-science-section"><h3>Prüffragen</h3><ul><li>Welche Vertrags- oder Objektunterlage enthält die maßgebliche Angabe?</li><li>Bezieht sich die Größe auf Monat, Jahr, Kaufpreis, Marktwert oder Darlehenssaldo?</li><li>Welche Kosten oder Risiken sind noch nicht enthalten?</li><li>Wie verändert sich das Ergebnis im konservativen Szenario?</li></ul></section><aside class="lab-practice-box"><strong>Hinweis</strong><p>Die Erläuterung dient der Orientierung und ersetzt keine Rechts-, Steuer- oder Finanzierungsberatung.</p></aside>`}
function numberRange(text){const m=String(text).replace(/\./g,'').match(/([0-9]+(?:,[0-9]+)?)\s*[–-]\s*([0-9]+(?:,[0-9]+)?)/);return m?[parseFloat(m[1].replace(',','.')),parseFloat(m[2].replace(',','.'))]:null}
function fmtPrice(v){return new Intl.NumberFormat('de-DE',{maximumFractionDigits:0}).format(Math.round(v/50)*50)+' €/m²'}
function locationBands(x){const r=numberRange(x.price);if(!r)return{etw:x.price,house:'stark grundstücks- und zustandsabhängig',mfh:'stark ertrags- und mietvertragsabhängig'};return{etw:`ca. ${fmtPrice(r[0])} bis ${fmtPrice(r[1])}`,house:`grob ca. ${fmtPrice(r[0]*1.05)} bis ${fmtPrice(r[1]*1.2)}; Grundstücksanteil separat bewerten`,mfh:`grob ca. ${fmtPrice(r[0]*.75)} bis ${fmtPrice(r[1]*.92)}; Ertragswert und Mietstruktur sind maßgeblich`}}
function locationDetail(x){const b=locationBands(x);return `<button data-location-back class="lab-back-button"><i class="fas fa-arrow-left"></i><span><small>Zurück zu</small>Standortanalysen</span></button><header class="lab-detail-header"><span class="lab-kicker">${esc(x.region)}</span><h2>${esc(x.name)}</h2><p class="lab-lead">F&G-Standorteinordnung für Kapitalanleger. Alle Bandbreiten sind grobe Orientierungswerte und keine Marktwertauskunft für ein konkretes Objekt.</p></header><section class="lab-location-price-grid"><article><span>Eigentumswohnungen</span><strong>${b.etw}</strong><p>Wohnungsgröße, Baujahr, WEG-Zustand, Vermietungsstatus und Mikrolage wirken unmittelbar auf den Quadratmeterpreis.</p></article><article><span>Ein- und Zweifamilienhäuser</span><strong>${b.house}</strong><p>Bei Häusern beeinflussen Grundstück, Nutzfläche, energetischer Zustand und Bebaubarkeit den Preis stärker als ein reiner Gebäudepreis je Quadratmeter.</p></article><article><span>Mehrfamilienhäuser</span><strong>${b.mfh}</strong><p>Bei Mehrfamilienhäusern liegen Quadratmeterpreise häufig unter vergleichbaren Einzelwohnungen. Entscheidend sind Jahresnettokaltmiete, Faktor, Leerstand, Capex und Aufteilungspotenzial.</p></article></section><div class="lab-location-deep"><section><h3>Mietniveau</h3><p>${esc(x.rent)}. Bestandsmieten, Neuvertragsmieten und möblierte Angebote müssen getrennt betrachtet werden.</p></section><section><h3>Renditeorientierung</h3><p>${esc(x.yield)}. Die tatsächliche Rendite hängt von Kaufpreis, Mietstatus, nicht umlagefähigen Kosten und Investitionsbedarf ab.</p></section><section><h3>Chancen</h3><p>${esc(x.chance)}</p></section><section><h3>Risiken</h3><p>${esc(x.risk)}</p></section><section><h3>Infrastruktur</h3><p>${esc(x.infra)}</p></section><section><h3>Zukunft und Bevölkerung</h3><p>${esc(x.future)} ${esc(x.population)}</p></section></div><section class="lab-science-section"><h3>Unsere Einordnung</h3><p>${esc(x.view)}</p><p>Für die Ankaufsprüfung sind auf Standortebene insbesondere ÖPNV-Anbindung, Arbeitgeberstruktur, Neubaupipeline, lokale Mietregulierung, Leerstandsrisiko und die Liquidität beim späteren Verkauf zu prüfen.</p></section>`}
function printCalculatorReport(id,fd,kpis,note,chart){const tool=tools.find(t=>t.id===id),fields=[];for(const [key,value] of fd.entries()){const input=workspace.querySelector(`[name="${CSS.escape(key)}"]`),label=input?.closest('.lab-field')?.querySelector('span')?.textContent||key;fields.push([label,value])}const win=window.open('','_blank');if(!win)return;win.document.write(`<!doctype html><html lang="de"><head><meta charset="utf-8"><title>${esc(tool.title)} – F&G</title><style>@page{size:A4;margin:15mm}*{box-sizing:border-box}body{font-family:Arial,sans-serif;color:#08082f;margin:0}.head{display:flex;align-items:center;gap:22px;border-bottom:3px solid #c69a20;padding-bottom:18px}.head img{width:90px;height:90px;object-fit:contain}.head h1{font-family:Georgia,serif;margin:0 0 7px;font-size:26px}.head p{margin:3px 0;color:#555}.section{margin-top:25px}.section h2{font-family:Georgia,serif;font-size:20px;border-bottom:1px solid #ddd;padding-bottom:8px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.card{border:1px solid #dfe3ea;border-radius:12px;padding:13px;break-inside:avoid}.card span{font-size:11px;color:#687086;display:block}.card strong{font-family:Georgia,serif;font-size:21px;display:block;margin-top:7px}.footer{margin-top:28px;border-top:1px solid #ddd;padding-top:14px;font-size:10px;color:#666}.note{background:#fff8df;border-left:4px solid #c69a20;padding:12px}.no-print{margin:16px 0}button{padding:10px 16px;background:#c69a20;border:0;border-radius:8px;font-weight:bold}@media print{.no-print{display:none}}</style></head><body><div class="no-print"><button onclick="window.print()">PDF speichern / drucken</button></div><header class="head"><img src="${location.origin}/images/fg-logo-gold-transparent.png"><div><h1>${esc(tool.title)}</h1><p>Fischer & Geserich Real Estate GmbH</p><p>Schützenstraße 30, 12165 Berlin · info@fg-realestate.de</p></div></header><section class="section"><h2>Eingaben</h2><div class="grid">${fields.map(x=>`<div class="card"><span>${esc(x[0])}</span><strong>${esc(x[1])}</strong></div>`).join('')}</div></section><section class="section"><h2>Ergebnisse</h2><div class="grid">${kpis.map(x=>`<div class="card"><span>${esc(x[0])}</span><strong>${esc(x[1])}</strong><small>${esc(x[2]||'')}</small></div>`).join('')}</div></section>${note?`<p class="note">${esc(note)}</p>`:''}<div class="footer">Unverbindliche Beispielrechnung. Sie ersetzt keine Rechts-, Steuer-, Finanzierungs- oder Anlageberatung. Berechnung erstellt am ${new Date().toLocaleDateString('de-DE')}.</div><script>window.onload=()=>setTimeout(()=>window.print(),300)<\/script></body></html>`);win.document.close()}

const articleGrid=root.querySelector('[data-article-grid]'),reader=root.querySelector('[data-article-reader]'),cats=['Alle',...new Set(DATA.articles.map(a=>a.category))];let activeCat='Alle';root.querySelector('[data-knowledge-filters]').innerHTML=cats.map(c=>`<button class="${c==='Alle'?'is-active':''}" data-cat="${c}">${c}</button>`).join('');function renderArticles(q=''){q=q.toLowerCase();articleGrid.hidden=false;reader.hidden=true;articleGrid.innerHTML=DATA.articles.filter(a=>(activeCat==='Alle'||a.category===activeCat)&&(a.title+' '+a.summary+' '+a.body).toLowerCase().includes(q)).map(a=>`<article class="lab-article-card"><span>${esc(a.category)}</span><h3>${esc(a.title)}</h3><p>${esc(a.summary)}</p><button data-article="${DATA.articles.indexOf(a)}">Fachartikel öffnen →</button></article>`).join('')||'<p class="lab-empty">Kein passender Fachartikel gefunden.</p>'};renderArticles();root.querySelector('[data-knowledge-search]').oninput=e=>renderArticles(e.target.value);root.querySelector('[data-knowledge-filters]').onclick=e=>{let b=e.target.closest('[data-cat]');if(!b)return;activeCat=b.dataset.cat;root.querySelectorAll('[data-cat]').forEach(x=>x.classList.toggle('is-active',x===b));renderArticles(root.querySelector('[data-knowledge-search]').value)};articleGrid.onclick=e=>{let b=e.target.closest('[data-article]');if(!b)return;let a=DATA.articles[+b.dataset.article];articleGrid.hidden=true;reader.hidden=false;reader.innerHTML=articleSections(a);reader.querySelector('[data-reader-back]').onclick=()=>renderArticles(root.querySelector('[data-knowledge-search]').value);reader.querySelector('[data-reader-tools]').onclick=()=>switchTab('tools');reader.scrollIntoView({behavior:'smooth',block:'start'})};

const locGrid=root.querySelector('[data-location-grid]'),locReader=root.querySelector('[data-location-reader]');function renderLoc(q=''){q=q.toLowerCase();locGrid.hidden=false;locReader.hidden=true;locGrid.innerHTML=DATA.locations.filter(x=>(x.name+' '+x.region).toLowerCase().includes(q)).map(x=>`<button type="button" class="lab-location-card" data-location="${DATA.locations.indexOf(x)}"><header><div><span>${esc(x.region)}</span><h3>${esc(x.name)}</h3></div><i class="fas fa-location-dot"></i></header><div class="lab-location-metrics"><p><span>Kaufpreise</span><strong>${esc(x.price)}</strong></p><p><span>Mietniveau</span><strong>${esc(x.rent)}</strong></p><p><span>Rendite</span><strong>${esc(x.yield)}</strong></p></div><span class="lab-card-action">Standortanalyse öffnen →</span></button>`).join('')||'<p class="lab-empty">Kein Standort gefunden.</p>'};renderLoc();root.querySelector('[data-location-search]').oninput=e=>renderLoc(e.target.value);locGrid.onclick=e=>{const b=e.target.closest('[data-location]');if(!b)return;const x=DATA.locations[+b.dataset.location];locGrid.hidden=true;locReader.hidden=false;locReader.innerHTML=locationDetail(x);locReader.querySelector('[data-location-back]').onclick=()=>renderLoc(root.querySelector('[data-location-search]').value);locReader.scrollIntoView({behavior:'smooth',block:'start'})};

const lexList=root.querySelector('[data-lexicon-list]'),lexReader=root.querySelector('[data-lexicon-reader]'),letters='ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('');root.querySelector('[data-az]').innerHTML=['Alle',...letters].map(x=>`<button class="${x==='Alle'?'is-active':''}" data-letter="${x}">${x}</button>`).join('');let letter='Alle';function renderLex(q=''){q=q.toLowerCase();lexList.hidden=false;lexReader.hidden=true;lexList.innerHTML=DATA.lexicon.filter(x=>(letter==='Alle'||x.term[0].toUpperCase()===letter)&&(x.term+' '+x.definition).toLowerCase().includes(q)).sort((a,b)=>a.term.localeCompare(b.term,'de')).map(x=>`<button type="button" class="lab-lexicon-entry" data-lex="${DATA.lexicon.indexOf(x)}"><strong>${esc(x.term)}</strong><span>${esc(x.definition)}</span><i class="fas fa-arrow-right"></i></button>`).join('')||'<p class="lab-empty">Kein Begriff gefunden.</p>'};renderLex();root.querySelector('[data-lexicon-search]').oninput=e=>renderLex(e.target.value);root.querySelector('[data-az]').onclick=e=>{let b=e.target.closest('[data-letter]');if(!b)return;letter=b.dataset.letter;root.querySelectorAll('[data-letter]').forEach(x=>x.classList.toggle('is-active',x===b));renderLex(root.querySelector('[data-lexicon-search]').value)};lexList.onclick=e=>{const b=e.target.closest('[data-lex]');if(!b)return;const x=DATA.lexicon[+b.dataset.lex];lexList.hidden=true;lexReader.hidden=false;lexReader.innerHTML=lexiconDetail(x);lexReader.querySelector('[data-lex-back]').onclick=()=>renderLex(root.querySelector('[data-lexicon-search]').value);lexReader.scrollIntoView({behavior:'smooth',block:'start'})};
})();
