(function(){
const root=document.querySelector('[data-investment-lab]');if(!root)return;
const DATA=JSON.parse(window.FG_LAB_DATA||'{}');
const eur=v=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(isFinite(v)?v:0);
const pct=v=>new Intl.NumberFormat('de-DE',{style:'percent',maximumFractionDigits:2}).format(isFinite(v)?v:0);
const de=v=>new Intl.NumberFormat('de-DE',{maximumFractionDigits:2}).format(isFinite(v)?v:0);
const parse=v=>{let s=String(v??'').replace(/\s|€|%/g,'');if(s.includes(','))s=s.replace(/\./g,'').replace(',','.');return parseFloat(s)||0};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function switchTab(name){root.querySelectorAll('[data-lab-tab]').forEach(b=>b.classList.toggle('is-active',b.dataset.labTab===name));root.querySelectorAll('[data-lab-panel]').forEach(p=>p.classList.toggle('is-active',p.dataset.labPanel===name));root.scrollIntoView({behavior:'smooth',block:'start'});}
root.addEventListener('click',e=>{let t=e.target.closest('[data-lab-tab],[data-lab-open]');if(t)switchTab(t.dataset.labTab||t.dataset.labOpen)});

const tools=[
{id:'investment',icon:'chart-line',title:'Investitionsrechner',desc:'Vollständige Objekt-, Finanzierungs-, Steuer- und Verlaufsrechnung.',link:'/investitionsrechner.html'},
{id:'afford',icon:'home',title:'Wie viel Immobilie kann ich mir leisten?',desc:'Monatsrate, Eigenkapital, Zins, Tilgung und Nebenkosten zu einem Kaufpreisrahmen verbinden.'},
{id:'closing',icon:'receipt',title:'Kaufnebenkostenrechner',desc:'Grunderwerbsteuer nach Bundesland, Notar, Grundbuch und Makler berechnen.'},
{id:'cashflow',icon:'coins',title:'Cashflow-Schnellcheck',desc:'Mit fünf Eingaben den monatlichen Überschuss vor Steuer abschätzen.'},
{id:'loan',icon:'landmark',title:'Darlehens- und Restschuldrechner',desc:'Annuität, Zins, Tilgung und Restschuld dynamisch berechnen.'},
{id:'yield',icon:'percentage',title:'Mietrenditerechner',desc:'Brutto- und Nettomietrendite mit transparenten Kosten.'},
{id:'afa',icon:'building',title:'AfA-Rechner',desc:'Gebäudeanteil, AfA-Basis und jährliche Abschreibung als Szenario.'},
{id:'tax',icon:'file-invoice-dollar',title:'Steuerersparnisrechner',desc:'Vereinfachte Steuerwirkung aus Zins, AfA und Überschuss.'},
{id:'rentgrowth',icon:'arrow-trend-up',title:'Mietsteigerungsrechner',desc:'Miete und kumulierte Erträge über die Zeit projizieren.'},
{id:'equity',icon:'wallet',title:'Eigenkapitalrechner',desc:'Erforderliches Eigenkapital aus Kaufpreis, Quote und Nebenkosten.'},
{id:'exit',icon:'door-open',title:'Exit-Rechner',desc:'Verkaufserlös, Restschuld, Kosten und Netto-Rückfluss modellieren.'},
{id:'interest',icon:'wave-square',title:'Zinsänderungsrechner',desc:'Was passiert mit Rate und Anschlussbelastung, wenn der Zins steigt?'},
{id:'value',icon:'city',title:'Immobilienwert-Prognose',desc:'Konservative Szenarien für Wertentwicklung und Endwert.'},
{id:'portfolio',icon:'layer-group',title:'Portfolio-Rechner',desc:'Mehrere Objekte als einfaches Portfolio zusammenfassen.'},
{id:'compare',icon:'scale-balanced',title:'Zwei Immobilien vergleichen',desc:'Kaufpreis, Miete, Cashflow und Rendite nebeneinanderstellen.'},
{id:'sensitivity',icon:'sliders',title:'Sensitivitätsanalyse',desc:'Zins, Miete, Leerstand und Kaufpreis als Tornado-Diagramm testen.'}
];
const grid=root.querySelector('[data-tool-grid]'), workspace=root.querySelector('[data-lab-workspace]');
function renderTools(q=''){let z=q.toLowerCase();grid.innerHTML=tools.filter(t=>(t.title+' '+t.desc).toLowerCase().includes(z)).map(t=>`<article class="lab-tool-card"><i class="fas fa-${t.icon}"></i><h3>${t.title}</h3><p>${t.desc}</p>${t.link?`<a href="${t.link}" class="lab-card-action">Öffnen <span>→</span></a>`:`<button class="lab-card-action" data-tool="${t.id}">Öffnen <span>→</span></button>`}</article>`).join('')}
renderTools();root.querySelector('[data-tool-search]').addEventListener('input',e=>renderTools(e.target.value));
grid.addEventListener('click',e=>{let b=e.target.closest('[data-tool]');if(b)openTool(b.dataset.tool)});
const field=(name,label,val='',suffix='',type='number')=>`<label class="lab-field"><span>${label}</span><div><input name="${name}" type="${type}" value="${val}" inputmode="decimal">${suffix?`<b>${suffix}</b>`:''}</div></label>`;
const formWrap=(tool,fields,extra='')=>`<div class="lab-work-head"><div><button data-close-tool class="lab-back">← Zur Toolbox</button><span class="lab-kicker">${tool.title.toUpperCase()}</span><h2>${tool.title}</h2><p>${tool.desc}</p></div></div><form data-tool-form="${tool.id}" class="lab-calc-form"><div class="lab-fields">${fields}</div>${extra}<div class="lab-form-actions"><button class="lab-btn lab-btn-gold" type="submit">Ergebnis berechnen</button></div></form><div data-tool-result class="lab-tool-result"></div>`;
function openTool(id){let t=tools.find(x=>x.id===id);workspace.hidden=false;grid.hidden=true;let f='',extra='';
 if(id==='afford')f=field('rate','Verfügbare Monatsrate',1800,'€')+field('equity','Eigenkapital',80000,'€')+field('interest','Sollzins p.a.',4.2,'%')+field('repay','Anfängliche Tilgung p.a.',2,'%')+field('costs','Kaufnebenkosten',10,'%');
 if(id==='closing')f=field('price','Kaufpreis',400000,'€')+`<label class="lab-field"><span>Bundesland</span><div><select name="state">${Object.entries(taxRates).map(([k,v])=>`<option value="${v}">${k} (${de(v)} %)</option>`).join('')}</select></div></label>`+field('broker','Makler inkl. MwSt.',3.57,'%')+field('notary','Notar',1.5,'%')+field('land','Grundbuch',0.5,'%');
 if(id==='cashflow')f=field('rent','Monatliche Nettokaltmiete',1200,'€')+field('loan','Darlehenssumme',250000,'€')+field('interest','Sollzins p.a.',4.2,'%')+field('repay','Tilgung p.a.',2,'%')+field('costs','Eigentümerkosten mtl.',250,'€');
 if(id==='loan')f=field('loan','Darlehen',300000,'€')+field('interest','Sollzins p.a.',4.2,'%')+field('repay','Anfängliche Tilgung p.a.',2,'%')+field('years','Zeitraum',10,'Jahre');
 if(id==='yield')f=field('price','Kaufpreis',300000,'€')+field('rent','Monatsnettokaltmiete',1200,'€')+field('costs','Nicht umlagefähige Kosten mtl.',180,'€')+field('vacancy','Mietausfall',2,'%')+field('reserve','Rücklage p.a.',1200,'€');
 if(id==='afa')f=field('price','Kaufpreis inkl. zuordenbarer Nebenkosten',350000,'€')+field('share','Gebäudeanteil',75,'%')+field('rate','AfA-Satz',2,'%')+field('years','Betrachtung',10,'Jahre');
 if(id==='tax')f=field('rent','Jahresnettokaltmiete',18000,'€')+field('costs','Abziehbare Kosten ohne Zins/AfA',3500,'€')+field('interest','Zinsen im Jahr',10000,'€')+field('afa','AfA im Jahr',6000,'€')+field('tax','Persönlicher Steuersatz',42,'%');
 if(id==='rentgrowth')f=field('rent','Aktuelle Monatsmiete',1200,'€')+field('growth','Mietsteigerung p.a.',2,'%')+field('years','Zeitraum',10,'Jahre');
 if(id==='equity')f=field('price','Kaufpreis',400000,'€')+field('costs','Nebenkosten',10,'%')+field('quote','Finanzierungsquote vom Kaufpreis',90,'%')+field('invest','Anfangsinvestitionen',20000,'€');
 if(id==='exit')f=field('value','Heutiger Immobilienwert',400000,'€')+field('growth','Wertsteigerung p.a.',2,'%')+field('years','Haltedauer',10,'Jahre')+field('debt','Restschuld beim Exit',250000,'€')+field('costs','Verkaufskosten',3.57,'%');
 if(id==='interest')f=field('debt','Restschuld',300000,'€')+field('repay','Tilgung p.a.',2,'%')+field('base','Basiszins',3.5,'%')+field('stress','Stresszins',5.5,'%');
 if(id==='value')f=field('value','Heutiger Wert',400000,'€')+field('growth','Wertsteigerung p.a.',2,'%')+field('years','Zeitraum',10,'Jahre');
 if(id==='portfolio')f=field('values','Gesamtwert Portfolio',1500000,'€')+field('debt','Gesamtdarlehen',900000,'€')+field('rent','Jahresnettokaltmiete',90000,'€')+field('costs','Eigentümerkosten p.a.',18000,'€')+field('service','Kapitaldienst p.a.',60000,'€');
 if(id==='compare')f=['a','b'].map((x,i)=>`<fieldset><legend>Objekt ${i+1}</legend>${field(x+'price','Kaufpreis',i?350000:300000,'€')}${field(x+'rent','Monatsmiete',i?1400:1200,'€')}${field(x+'costs','Kosten mtl.',i?220:180,'€')}</fieldset>`).join('');
 if(id==='sensitivity')f=field('price','Kaufpreis',400000,'€')+field('rent','Monatsmiete',1600,'€')+field('loan','Darlehen',360000,'€')+field('interest','Zins p.a.',4,'%')+field('repay','Tilgung p.a.',2,'%')+field('costs','Kosten mtl.',250,'€');
 workspace.innerHTML=formWrap(t,f,extra);workspace.scrollIntoView({behavior:'smooth',block:'start'});workspace.querySelector('[data-close-tool]').onclick=()=>{workspace.hidden=true;grid.hidden=false};workspace.querySelector('form').onsubmit=e=>{e.preventDefault();calcTool(id,new FormData(e.target),workspace.querySelector('[data-tool-result]'))};}
const taxRates={'Baden-Württemberg':5,'Bayern':3.5,'Berlin':6,'Brandenburg':6.5,'Bremen':5,'Hamburg':5.5,'Hessen':6,'Mecklenburg-Vorpommern':6,'Niedersachsen':5,'Nordrhein-Westfalen':6.5,'Rheinland-Pfalz':5,'Saarland':6.5,'Sachsen':5.5,'Sachsen-Anhalt':5,'Schleswig-Holstein':6.5,'Thüringen':6.5};
function annuity(loan,interest,repay,years=1){let rate=loan*(interest+repay)/12,debt=loan,ints=0,prin=0;for(let m=0;m<years*12&&debt>0;m++){let i=debt*interest/12,p=Math.min(debt,Math.max(0,rate-i));ints+=i;prin+=p;debt-=p}return{rate,debt,interest:ints,principal:prin}}
function resultHtml(kpis,note='',chart=''){return `<div class="lab-result-kpis">${kpis.map(k=>`<article><span>${k[0]}</span><strong>${k[1]}</strong><small>${k[2]||''}</small></article>`).join('')}</div>${chart}${note?`<p class="lab-result-note">${note}</p>`:''}<div class="lab-result-actions"><button data-save-calc class="lab-btn lab-btn-ghost">Lokal speichern</button><button onclick="window.print()" class="lab-btn lab-btn-ghost">Als PDF drucken</button><a href="/ankaufsberatung.html" class="lab-btn lab-btn-gold">Ergebnis besprechen</a></div>`}
function calcTool(id,fd,out){let v=k=>parse(fd.get(k)),k=[],note='',chart='';
 if(id==='afford'){let rate=v('rate'),e=v('equity'),i=v('interest')/100,t=v('repay')/100,c=v('costs')/100,loan=rate*12/(i+t),price=(loan+e)/(1+c);k=[['Möglicher Kaufpreis',eur(price),'Orientierungswert'],['Darlehensrahmen',eur(loan)],['Gesamtbudget inkl. Nebenkosten',eur(price*(1+c))],['Monatliche Rate',eur(rate)]]}
 if(id==='closing'){let p=v('price'),tax=v('state'),a=p*tax/100,b=p*v('broker')/100,n=p*v('notary')/100,l=p*v('land')/100,total=a+b+n+l;k=[['Nebenkosten gesamt',eur(total),pct(total/p)+' des Kaufpreises'],['Grunderwerbsteuer',eur(a)],['Makler',eur(b)],['Notar & Grundbuch',eur(n+l)],['Gesamtinvestition',eur(p+total)]]}
 if(id==='cashflow'){let rent=v('rent'),a=annuity(v('loan'),v('interest')/100,v('repay')/100),cf=rent-a.rate-v('costs');k=[['Cashflow pro Monat',eur(cf),cf>=0?'rechnerischer Überschuss':'rechnerischer Zuschuss'],['Annuität pro Monat',eur(a.rate)],['Miete',eur(rent)],['Eigentümerkosten',eur(v('costs'))]]}
 if(id==='loan'){let a=annuity(v('loan'),v('interest')/100,v('repay')/100,v('years'));k=[['Monatliche Annuität',eur(a.rate)],['Restschuld',eur(a.debt)],['Gezahlte Zinsen',eur(a.interest)],['Getilgt',eur(a.principal)]]}
 if(id==='yield'){let annual=v('rent')*12,gross=annual/v('price'),net=(annual*(1-v('vacancy')/100)-v('costs')*12-v('reserve'))/v('price');k=[['Bruttomietrendite',pct(gross)],['Nettomietrendite',pct(net)],['Jahresnettokaltmiete',eur(annual)],['Nettoertrag',eur(net*v('price'))]]}
 if(id==='afa'){let base=v('price')*v('share')/100,annual=base*v('rate')/100;k=[['AfA-Basis',eur(base)],['AfA pro Jahr',eur(annual)],['Kumuliert',eur(annual*v('years'))],['Nicht abschreibbarer Anteil',eur(v('price')-base)]];note='Vereinfachtes Szenario. Steuerliche Zuordnung und anwendbarer AfA-Satz müssen individuell geprüft werden.'}
 if(id==='tax'){let income=v('rent')-v('costs')-v('interest')-v('afa'),tax=income*v('tax')/100;k=[['Steuerliches Ergebnis',eur(income)],['Vereinfachte Steuerwirkung',eur(tax)],['Liquidität vor Tilgung',eur(v('rent')-v('costs')-v('interest')-tax)],['AfA',eur(v('afa'))]]}
 if(id==='rentgrowth'){let r=v('rent'),g=v('growth')/100,y=v('years'),end=r*Math.pow(1+g,y),cum=0;for(let n=1;n<=y;n++)cum+=r*12*Math.pow(1+g,n-1);k=[['Monatsmiete am Ende',eur(end)],['Jahresmiete am Ende',eur(end*12)],['Kumulierte Miete',eur(cum)],['Gesamtanstieg',pct(end/r-1)]]}
 if(id==='equity'){let p=v('price'),cost=p*v('costs')/100,loan=p*v('quote')/100,need=p+cost+v('invest')-loan;k=[['Erforderliches Eigenkapital',eur(need)],['Darlehen',eur(loan)],['Nebenkosten',eur(cost)],['Gesamtinvestition',eur(p+cost+v('invest'))]]}
 if(id==='exit'){let end=v('value')*Math.pow(1+v('growth')/100,v('years')),cost=end*v('costs')/100,net=end-cost-v('debt');k=[['Prognostizierter Verkaufspreis',eur(end)],['Verkaufskosten',eur(cost)],['Restschuld',eur(v('debt'))],['Netto-Rückfluss',eur(net)]]}
 if(id==='interest'){let base=annuity(v('debt'),v('base')/100,v('repay')/100),stress=annuity(v('debt'),v('stress')/100,v('repay')/100);k=[['Rate Basiszins',eur(base.rate)],['Rate Stresszins',eur(stress.rate)],['Mehrbelastung pro Monat',eur(stress.rate-base.rate)],['Mehrbelastung pro Jahr',eur((stress.rate-base.rate)*12)]]}
 if(id==='value'){let end=v('value')*Math.pow(1+v('growth')/100,v('years'));k=[['Endwert Szenario',eur(end)],['Nominaler Zuwachs',eur(end-v('value'))],['Wachstum gesamt',pct(end/v('value')-1)],['Startwert',eur(v('value'))]]}
 if(id==='portfolio'){let net=v('rent')-v('costs'),dscr=net/v('service'),ltv=v('debt')/v('values');k=[['Portfoliowert',eur(v('values'))],['LTV',pct(ltv)],['Nettoertrag vor Finanzierung',eur(net)],['DSCR',de(dscr)+'x']];note='Vereinfachte Portfoliosicht. Banken können DSCR und Beleihungswerte anders definieren.'}
 if(id==='compare'){let calc=x=>({gross:v(x+'rent')*12/v(x+'price'),net:v(x+'rent')*12-v(x+'costs')*12});let a=calc('a'),b=calc('b');k=[['Bruttorendite Objekt 1',pct(a.gross)],['Bruttorendite Objekt 2',pct(b.gross)],['Nettoertrag Objekt 1',eur(a.net)],['Nettoertrag Objekt 2',eur(b.net)]]}
 if(id==='sensitivity'){let base=v('rent')*12-v('costs')*12-v('loan')*(v('interest')+v('repay'))/100;let scenarios=[['Zins +1 %-Punkt',base-v('loan')*.01],['Miete -10 %',base-v('rent')*12*.1],['Kosten +20 %',base-v('costs')*12*.2],['Kaufpreis -10 %',base],['Miete +3 %',base+v('rent')*12*.03]];let max=Math.max(...scenarios.map(x=>Math.abs(x[1]-base)),1);chart=`<div class="lab-tornado"><h3>Abweichung vom Basis-Cashflow (${eur(base)} p.a.)</h3>${scenarios.map(s=>{let d=s[1]-base,w=Math.abs(d)/max*48;return `<div><span>${s[0]}</span><i class="${d>=0?'pos':'neg'}" style="width:${w}%"></i><b>${eur(d)}</b></div>`}).join('')}</div>`;k=[['Basis-Cashflow p.a.',eur(base)],['Basis-Cashflow mtl.',eur(base/12)],['Stärkster negativer Effekt',eur(Math.min(...scenarios.map(x=>x[1]-base)))],['Miete +3 %',eur(base+v('rent')*12*.03)]]}
 out.innerHTML=resultHtml(k,note,chart);out.scrollIntoView({behavior:'smooth',block:'nearest'});out.querySelector('[data-save-calc]').onclick=()=>saveCalc(id,k)}
function saveCalc(id,k){let arr=JSON.parse(localStorage.getItem('fgLabSaved')||'[]');arr.unshift({id,title:tools.find(t=>t.id===id)?.title,date:new Date().toLocaleDateString('de-DE'),k});arr=arr.slice(0,12);localStorage.setItem('fgLabSaved',JSON.stringify(arr));renderSaved()}
function renderSaved(){let box=root.querySelector('[data-lab-saved]'),arr=JSON.parse(localStorage.getItem('fgLabSaved')||'[]');box.innerHTML=arr.length?`<div class="lab-section-head"><div><span class="lab-kicker">GESPEICHERTE BERECHNUNGEN</span><h2>Auf diesem Gerät gespeichert</h2></div><button class="lab-clear" data-clear-saved>Alle löschen</button></div><div class="lab-saved-grid">${arr.map((x,i)=>`<article><small>${x.date}</small><h3>${x.title}</h3>${x.k.slice(0,2).map(y=>`<p><span>${y[0]}</span><strong>${y[1]}</strong></p>`).join('')}<button data-delete-saved="${i}">Löschen</button></article>`).join('')}</div>`:'';box.querySelector('[data-clear-saved]')?.addEventListener('click',()=>{localStorage.removeItem('fgLabSaved');renderSaved()});box.querySelectorAll('[data-delete-saved]').forEach(b=>b.onclick=()=>{arr.splice(+b.dataset.deleteSaved,1);localStorage.setItem('fgLabSaved',JSON.stringify(arr));renderSaved()})}renderSaved();

const articleGrid=root.querySelector('[data-article-grid]'), reader=root.querySelector('[data-article-reader]'), cats=['Alle',...new Set(DATA.articles.map(a=>a.category))];let activeCat='Alle';root.querySelector('[data-knowledge-filters]').innerHTML=cats.map(c=>`<button class="${c==='Alle'?'is-active':''}" data-cat="${c}">${c}</button>`).join('');function renderArticles(q=''){q=q.toLowerCase();articleGrid.hidden=false;reader.hidden=true;articleGrid.innerHTML=DATA.articles.filter(a=>(activeCat==='Alle'||a.category===activeCat)&&(a.title+' '+a.summary+' '+a.body).toLowerCase().includes(q)).map((a,i)=>`<article class="lab-article-card"><span>${a.category}</span><h3>${a.title}</h3><p>${a.summary}</p><button data-article="${DATA.articles.indexOf(a)}">Artikel lesen →</button></article>`).join('')};renderArticles();root.querySelector('[data-knowledge-search]').oninput=e=>renderArticles(e.target.value);root.querySelector('[data-knowledge-filters]').onclick=e=>{let b=e.target.closest('[data-cat]');if(!b)return;activeCat=b.dataset.cat;root.querySelectorAll('[data-cat]').forEach(x=>x.classList.toggle('is-active',x===b));renderArticles(root.querySelector('[data-knowledge-search]').value)};articleGrid.onclick=e=>{let b=e.target.closest('[data-article]');if(!b)return;let a=DATA.articles[+b.dataset.article];articleGrid.hidden=true;reader.hidden=false;reader.innerHTML=`<button data-reader-back class="lab-back">← Zur Übersicht</button><span class="lab-kicker">${a.category}</span><h2>${a.title}</h2><p class="lab-lead">${a.summary}</p><p>${a.body}</p><aside><strong>Praxis-Hinweis</strong><p>Nutzen Sie passende Rechner im Investment Lab und prüfen Sie die Annahmen anschließend anhand der Objektunterlagen.</p></aside><div class="lab-reader-links"><button data-reader-tools class="lab-btn lab-btn-gold">Passenden Rechner öffnen</button><a href="/angebote.html" class="lab-btn lab-btn-ghost">Aktuelle Angebote</a></div>`;reader.querySelector('[data-reader-back]').onclick=()=>renderArticles(root.querySelector('[data-knowledge-search]').value);reader.querySelector('[data-reader-tools]').onclick=()=>switchTab('tools');reader.scrollIntoView({behavior:'smooth'})};

const locGrid=root.querySelector('[data-location-grid]');function renderLoc(q=''){q=q.toLowerCase();locGrid.innerHTML=DATA.locations.filter(x=>(x.name+' '+x.region).toLowerCase().includes(q)).map(x=>`<article class="lab-location-card"><header><div><span>${x.region}</span><h3>${x.name}</h3></div><i class="fas fa-location-dot"></i></header><div class="lab-location-metrics"><p><span>Kaufpreise</span><strong>${x.price}</strong></p><p><span>Mietniveau</span><strong>${x.rent}</strong></p><p><span>Rendite</span><strong>${x.yield}</strong></p></div><details><summary>Analyse anzeigen</summary><dl><dt>Chancen</dt><dd>${x.chance}</dd><dt>Risiken</dt><dd>${x.risk}</dd><dt>Infrastruktur</dt><dd>${x.infra}</dd><dt>Zukunft</dt><dd>${x.future}</dd><dt>Bevölkerung</dt><dd>${x.population}</dd><dt>Unsere Einordnung</dt><dd>${x.view}</dd></dl><a href="${x.source}" target="_blank" rel="noopener">Quelle / Marktbericht ↗</a></details></article>`).join('')};renderLoc();root.querySelector('[data-location-search]').oninput=e=>renderLoc(e.target.value);

const lexList=root.querySelector('[data-lexicon-list]'),letters='ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('');root.querySelector('[data-az]').innerHTML=['Alle',...letters].map(x=>`<button data-letter="${x}">${x}</button>`).join('');let letter='Alle';function renderLex(q=''){q=q.toLowerCase();lexList.innerHTML=DATA.lexicon.filter(x=>(letter==='Alle'||x.term[0].toUpperCase()===letter)&&(x.term+' '+x.definition).toLowerCase().includes(q)).sort((a,b)=>a.term.localeCompare(b.term,'de')).map(x=>`<details><summary><strong>${x.term}</strong><span>+</span></summary><p>${x.definition}</p></details>`).join('')};renderLex();root.querySelector('[data-lexicon-search]').oninput=e=>renderLex(e.target.value);root.querySelector('[data-az]').onclick=e=>{let b=e.target.closest('[data-letter]');if(!b)return;letter=b.dataset.letter;root.querySelectorAll('[data-letter]').forEach(x=>x.classList.toggle('is-active',x===b));renderLex(root.querySelector('[data-lexicon-search]').value)};
})();
